# Generated by Django 5.1.1 on 2024-12-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='due_date',
        ),
    ]
