# Generated by Django 5.1.1 on 2024-12-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_savings_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='reminder',
        ),
    ]
