# Generated by Django 5.1.1 on 2024-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_savings_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='reminder',
            field=models.DateField(blank=True, null=True),
        ),
    ]
