# Generated by Django 5.1.1 on 2024-12-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_savings_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
